print("Please enter in this format if its 2/3 enter x=2  y=3")
x=int(input("enter x:"))
y=int(input("enter y:"))
m=int(input("enter total income:"))
print("If u want to find out 1/4th part Please enter in this format p=1  j=4")
p=int(input("enter p:"))
j=int(input("enter j:"))
wi=(m)*(y/x)

print(int(int(wi)*(p/j)))
